planner_expert_final_l2_error_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.planner_expert_final_l2_error.PlannerExpertFinalL2ErrorStatistics
  _convert_: 'all'
  name: 'planner_expert_final_l2_error'
  category: 'Planning'

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    planner_expert_average_l2_error_metric: planner_expert_average_l2_error_statistics
