planner_expert_average_heading_error_statistics:
  _target_: nuplan.planning.metrics.evaluation_metrics.common.planner_expert_average_heading_error.PlannerExpertAverageHeadingErrorStatistics
  _convert_: 'all'
  name: 'planner_expert_average_heading_error'
  category: 'Planning'

  required_metrics:
    # Parameter: base metric name and other high level metrics used in this metric
    planner_expert_average_l2_error_metric: planner_expert_average_l2_error_statistics
